### ISSUE TITLE
script='main.py'

### ISSUE THREAD

**Issue by scf819** [Jomigi/Cone_angle_artifact_reduction#1]
Is   'main.py'  missing?

**Comment by FelixLucka** [comment]
Thanks for spotting this. You are probably referring to line 17 in [validation.sh](https://github.com/Jomigi/Cone_angle_artifact_reduction/blob/e4239989386385db831f43456d1961701ef45ca3/code/validation.sh#L17). I  think it should be changed to train.py, but even then, I don't know if the rest of this script will run (it could be outdated and we just forgot to update or delete it). Unfortunately, I cannot checkout all the data and code and rerun everything at the moment.
